name: bepo_test_github_action_workflows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout # 1
        uses: actions/checkout@v3

      - name: Set up JDK 11 # 2
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      ## create db-connection.yml
      - name: make db-connection.yml
        run: |
          # create db-connection.yml
          cd ./src/main/resources
  
          # db-connection.yml 파일 생성
          touch ./db-connection.yml
  
          # GitHub-Actions 에서 설정한 값을 db-connection.yml 파일에 쓰기
          echo "${{ secrets.DB }}" >> ./db-connection.yml
        shell: bash

      # gradle build  -> Dockerfile 에서 진행
      - name: Build with Gradle
        run: ./gradlew bootJar

        ## gradle build and docker image 빌드 및 도커허브에 push
      - name: docker build and push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t roomdoor/bepo-test .
          docker push roomdoor/bepo-test

#   배포 Job
  deploy:
    needs: build  # build 후에 실행되도록 정의
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            sudo docker rm -f $(docker ps -qa)
            sudo docker pull roomdoor/bepo-test:latest
            sudo docker run --name bepo-test -p 8080:8080 roomdoor/bepo-test:latest