name: bepo_test_github_action_workflows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout # 1
        uses: actions/checkout@v3

      - name: Set up JDK 11 # 2
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      ## create db-connection.yml
      - name: make db-connection.yml
        run: |
          # create db-connection.yml
          cd ./src/main/resources
  
          # db-connection.yml 파일 생성
          touch ./db-connection.yml
  
          # GitHub-Actions 에서 설정한 값을 db-connection.yml 파일에 쓰기
          echo "${{ secrets.DB }}" >> ./db-connection.yml
        shell: bash

      ## gradle build  -> Dockerfile 에서 진행
      ##  - name: Build with Gradle
      ##  run: ./gradlew bootJar

        ## gradle build and docker image 빌드 및 도커허브에 push
      - name: web docker build and push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t roomdoor/bepo-test .
          docker push roomdoor/bepo-test

  #      uses: mr-smithers-excellent/docker-build-push@v5
  #      with:
  #        image: roomdoor/bepo-test
  #        registry: docker.io
  #        username: ${{ secrets.DOCKER_USERNAME }}
  #        password: ${{ secrets.DOCKER_PASSWORD }}

      ## 도커 컨테이너 실행
      - name: docker run
        run: docker run --name bepo-test -p 9090:9090 roomdoor/test-bepo-test

